### ISSUE TITLE
Enchanter keeping stuff in inv.

### ISSUE THREAD

**Issue by Getraaa** [TangoTek/TekTopia-Community#171] opened 2019-05-29 18:24 UTC
For some reason my enchanters keep every enchanted thing in their inv.  
![2019-05-29_20 19 24](https://user-images.githubusercontent.com/35698012/58581405-c6274380-824f-11e9-8366-a179e548918c.png)

**Comment by JohnyDL** [comment] 2019-05-30 00:08
Possibly related to #65 I noticed he needed 4 books to return them, And is a duplicate of #102

**Comment by TangoTek** [comment] 2019-06-01 08:26
Fixed. Plus new drop off system coming.

**Closed as completed by TangoTek** 2019-06-01 08:26 UTC
