### ISSUE TITLE
Druids mainly, but also other villagers starving a LOT

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#617] opened 2019-07-04 21:05 UTC
**Describe the bug**
We're suffering a lot of villagers starving. In the grand scheme of things, at 350-odd villagers, it's not a large percentage, but still 2-3 on average every game day. Food isn't an issue. We've got a couple of foods that we have massive excess of, and are actively making about 8 more types of food. I think clerics highest class that are starving, but they don't die as much because if it's daytime, they heal themselves through it. they do lie there and starve to death if its night however as they are asleep. Makani has observed them for about an hour, a few different starving villagers, and has noticed that it seems to be mainly higher level villagers.

**To Reproduce**
1. Get a village
2. Grow it really large
3. Watch clerics and druids starve to death, even though there is food available.

**Expected behavior**
I'd expect all classes to not starve if there is even one food option. As far as I believe lacking food choices causes unhappiness, not starving.

**Screenshots**

** Server/Location **
Main 1
x=-3980 z=2042

**Additional context**
I'd consider this a pretty high priority bug as it seems to be taking out a lot of our high level druids. This is my main concern, as the replacements then can't keep up with the miners and the mineshafts break through length....

**Comment by Hedkracka** [comment] 2019-07-04 22:25
i lost my bard to starve damage while he slept
![2019-07-04_23 10 40](https://user-images.githubusercontent.com/20891568/60689238-09aa4880-9eb3-11e9-8dd4-42273d674d57.png)

Glad the cords were there cos i confirmed he was in bed

**Comment by Nightshae** [comment] 2019-07-05 05:35
I lost what I believe to be a level 100 druid to this, also while he was in bed according to the cords.  Plenty of food available, no idea why he wasn't eating.


Could this have something to do with level 100 villagers?  I lost two bards in less than 60 seconds to this same bug, but that occurred back about 3-4 jars ago.  Both were level 100.



![2019-07-04_16 56 25](https://user-images.githubusercontent.com/51100661/60700155-4706da00-9ea3-11e9-9f04-854bf59c2387.png)

**Comment by Sobertron** [comment] 2019-07-05 08:05
To continue shams post. In the last hour we lost 4 druids, a cleric and a bard.

What i have observed is that they continue to do their jobs to the point where they are hungry. If this occurs just before nightfall  or during the night then they will not go to storage and get food. 

![2019-07-05_08 32 13](https://user-images.githubusercontent.com/49371154/60707376-7d744180-9f03-11e9-82af-68a10e8552e6.png)

This Druid walked right by the storage to get to his bed. The only reason he survived the night is because a cleric was healing him. I noticed this and unloaded the village through the night. When morning hit i returned to the village and this same druid went to storage to get food. This leads me to believe that it is a problem with the time of day they are getting hungry. Something in their AI is telling them to not get food outside of daylight hours.

![2019-07-05_08 17 33](https://user-images.githubusercontent.com/49371154/60707363-73524300-9f03-11e9-942a-891cadea2662.png)

**Comment by Annie8472** [comment] 2019-07-05 08:12
Druids (and a bard) were very hungry and refusing to eat again. I find that if I turn off every available duty that they will usually go eat if it is not getting close to night. I almost lost one just now and might have lost one within the last 24 hours. 

And I just found another level 100 druid refusing to eat; duties turned off will see if she starts to eat in the morning. I just checked the level of the first druid who is also a level 100. The druid began to eat in the morning.

While in the storage room, I found a hungry miner just standing there. He would not eat until I yet again unchecked every duty at which time he grabbed food and ran.

**Comment by Shamshalabim** [comment] 2019-07-05 13:35
That last with the miner often seems to be a pathing issue. If you check next time and see if they are stood directly above the end of a mineshaft...

**Comment by Shamshalabim** [comment] 2019-07-05 13:35
@Annie8472

**Comment by Sobertron** [comment] 2019-07-05 15:17
Looks like we need to add butchers to the list.

![2019-07-05_16 15 20](https://user-images.githubusercontent.com/49371154/60731770-51c37c80-9f40-11e9-878c-88944e3319e1.png)

As these deaths also happened at night I continue to believe that it is an issue with hungry villagers going to bed because they cannot go to the storage to get food outside of the work day.

**Comment by ghost** [comment] 2019-07-05 15:40
I found my villager was taking starvation damage while sleeping , then I broke his bed and he went to the storage room to eat. I think the problem is in the system of priorities of their tasks.

**Comment by Annie8472** [comment] 2019-07-05 17:09
> That last with the miner often seems to be a pathing issue. If you check next time and see if they are stood directly above the end of a mineshaft...

Thanks, Sham. I checked the location of the mines and they are not directly below our storage room. It was worth a shot and I really appreciate your help!

@Shamshalabim

**Comment by Annie8472** [comment] 2019-07-05 17:30
Another miner... This one was standing in the streets.

**Comment by Sobertron** [comment] 2019-07-05 19:41
Just had a thought on this. It appears this bug is effecting villagers who do not drop off items in storage (mostly druids, bards, and clerics). I wonder if it has to do with that fact that gathering/crafting villagers visit the storage at the end of the day to drop off items they may also be picking up food. 

As druids, clerics, and bard have no other reason to visit the storage building other than to get food, they have no need for an end of day delivery, which means they may be missing an opportunity to get food before bed, which is when most of them are dying.

**Comment by Shamshalabim** [comment] 2019-07-06 12:37
Did you seriously thumbs up your own comment?? 📦

**Comment by Leo8472** [comment] 2019-07-07 08:17
High level villagers getting stuck out somewhere and not eating, even though there is plenty of food in the food chest in storage.
![2019-07-07_00 35 19](https://user-images.githubusercontent.com/52061802/60765792-ba038280-a054-11e9-925e-d3df473ae778.png)

**Comment by Leo8472** [comment] 2019-07-07 08:19
Coordinates of our latest high skill villager starving to death in the photo.
![2019-07-07_00 22 08](https://user-images.githubusercontent.com/52061802/60765830-457d1380-a055-11e9-8ba4-fffcbeba144f.png)

**Comment by Annie8472** [comment] 2019-07-07 08:25
![2019-07-07_01 22 10](https://user-images.githubusercontent.com/51523021/60765868-e370de00-a055-11e9-91e4-180afbcb978a.png)
It looks like the place where Leo saw a villager die is actually owned by a different villager. Coincidence?

**Comment by RensSwag2001** [comment] 2019-07-07 16:09
I had this too! Just reacting as an upvote <3

**Comment by Annie8472** [comment] 2019-07-08 06:56
Rocket tells me we lost another five butchers to starvation the evening. Our storage room is overflowing with produce in single chests on the floor.

**Comment by Snodderz** [comment] 2019-07-08 20:46
There's a few villager types that don't seem to gather as much food as others - eg, my Ranchers are carrying 5+ potatoes, 5+ carrots, mutton, steak and a golden carrot, where as my druids will grab just one golden carrot and leave. I think Sobertron hit the nail on the head as the types that don't seem to have as much in their inventories are the ones that don't deliver. Also agree with how they don't gather food during night hours. There's a surplus of all food types in storage...

**Comment by TangoTek** [comment] 2019-07-09 21:49
This should be fixed in 1.0.59

**Closed as completed by TangoTek** 2019-07-09 21:49 UTC
