### ISSUE TITLE
Signs on chests in storage room freezes villagers

### ISSUE THREAD

**Issue by NoirFaeNocturne** [TangoTek/TekTopia-Community#677] opened 2019-07-12 00:27 UTC
**Describe the bug**
When signs are added to chests in the Storage room (ex. as labels for chests contents), villagers will seem not stop accessing them over the coarse of a few mc days,and somehow results in villagers just standing around unable to move, often with items cycling/glitching in their hands. This can cause them to stay in just any spot in the village waiting, often starving themselves if they have no food in their inventory. Sometimes they will sleep, but some villagers just stay standing through the whole night and day inside of their rooms.
Randomly it seems some villagers will keep functioning (Ex. Guards and occasionally Clerics) until they finally need to restock on food, then they will stay in place waiting as well.

**To Reproduce**
1. Add signs to Storage Room chests.
2. Wait until next morning or a few mc days later.

**Expected behavior**
For villagers to not acknowledge signs for labeling, or to put items in chests as labeled. (Primarily just ignore the signs on the chests until some kind of chest labeling is added later on, if ever)

** Server/Location **
What If Sever 2, 
-480, 79, -22

**Additional context**
This was randomly discovered as we had labeled some chests and not others as a way of keeping track of items to sell. We tried leading villagers on leads, removing town hall marker, leaving the vicinity for a few minutes, then returning and adding the marker back, removing and returning storage marker, and even removing double stacked chests, until finally removing the signs which fixed them up the next morning and they all returned to proper behavior.
![2019-07-11_16 33 51](https://user-images.githubusercontent.com/52805054/61093718-be3af180-a400-11e9-93cd-191446f9ac4b.png)
![2019-07-11_16 35 12](https://user-images.githubusercontent.com/52805054/61093719-be3af180-a400-11e9-8885-ef57a48d7c89.png)
![2019-07-11_16 37 12](https://user-images.githubusercontent.com/52805054/61093721-be3af180-a400-11e9-8499-6badeb35d9fc.png)
![2019-07-11_16 37 28](https://user-images.githubusercontent.com/52805054/61093722-bed38800-a400-11e9-9445-91b92c7abbf1.png)
![2019-07-11_16 43 56](https://user-images.githubusercontent.com/52805054/61093724-bed38800-a400-11e9-9897-7ed5803a83d6.png)
![2019-07-11_16 52 10](https://user-images.githubusercontent.com/52805054/61093725-c004b500-a400-11e9-9d90-98165719f915.png)
![2019-07-11_16 53 34](https://user-images.githubusercontent.com/52805054/61093726-c09d4b80-a400-11e9-83ab-0b3d259cc5ab.png)
![2019-07-11_16 54 56](https://user-images.githubusercontent.com/52805054/61093728-c1ce7880-a400-11e9-82bc-5b246366310a.png)
![2019-07-11_16 56 26](https://user-images.githubusercontent.com/52805054/61093729-c2670f00-a400-11e9-9d8a-b1c6d2838f6a.png)
![2019-07-11_16 56 36](https://user-images.githubusercontent.com/52805054/61093735-c85cf000-a400-11e9-9148-6bf6825832cb.png)

**Comment by LadyGwynn** [comment] 2019-07-12 01:48
I encountered this when I redid my storage room also. The issue is that the signs block the villagers from accessing the chests, so they simply freeze in place, trying to find a way to access the blocked off chests. It's not the prettiest fix, but I moved my signs to the top of the chests and they are usable now.

**Comment by TangoTek** [comment] 2019-07-14 06:03
Thanks for this one.  Turned out to be a Minecraft bug.
Fixed in 1.0.62

**Closed as completed by TangoTek** 2019-07-14 06:03 UTC
