### ISSUE TITLE
Smeltable items coming out green when fuel/smeltable isnt

### ISSUE THREAD

**Issue by TangoTek** [TangoTek/TekTopia-Community#188] opened 2019-05-29 23:55 UTC

**Comment by JohnyDL** [comment] 2019-05-30 00:14
I get the ore needing to be green to make green ingots but the fuel shouldn't matter in my opinion, heat is heat.

**Comment by tomerorian** [comment] 2019-05-30 00:58
This is a duplicate of https://github.com/TangoTek/TekTopia-Community/issues/124

**Closed as completed** 2019-06-01 08:24 UTC
Labels: duplicate
