### ISSUE TITLE
Lumberjacks pick up saplings

### ISSUE THREAD

**Issue by AbsentAbigail** [TangoTek/TekTopia-Community#264] opened 2019-06-02 12:45 UTC
**Describe the bug**
Lumberjacks pick up saplings, even when they have a lot.
This leads to the inventory getting really full and pretty much putting them on a death timer, because they'll run out of inventory space to pick up food and they eventually starve.

I do not know under what conditions they pick up saplings, but it does seem frequent enough to fill up the inventory at a decent pace.

**To Reproduce**
1. Have a lumberjack and a forest

**Expected behavior**
Lumberjack will cease picking up saplings when he/she has enough.

**Screenshots**
Inventory of my LJ:
https://imgur.com/a/ZhDr8Nn

** Server/Location **
Server 2
TH Marker "Aerialis": -6119 88 -5538

**Comment by JohnyDL** [comment] 2019-06-02 12:50
Duplicate of #230

**Comment by hehe3301** [comment] 2019-06-02 14:19
Confirmed this still happens, 2 lumberjack deaths of starvation

**Comment by Geex204** [comment] 2019-06-02 14:49
Same, so even its a dup of 230, that one is closed because assumed fixed, which it clearly isnt.

**Comment by JohnyDL** [comment] 2019-06-02 17:03
It's fixed for the 1.0.19 release. Look at when he said fixed (friday) and when 1.0.18 came out (wednesday) he can't magic the code into the past. Tango closes things when he's coded them not when the patch is out for us, Doing anything else would be a nightmare. This is a duplicate wait for the release before saying the fix didn't work.

And even if it's not fixed in an update you should be commenting on the initial bug report and getting it to be reopened as it's not fixed (or at the very least not complaining when the link between the bug reports is posted) so that the bug can be tracked from one fix to the next

**Closed as completed** 2019-06-02 17:32 UTC
Labels: duplicate
