### ISSUE TITLE
Lumberjacks replant without removing entire tree

### ISSUE THREAD

**Issue by IridescentShadow** [TangoTek/TekTopia-Community#85] opened 2019-05-27 10:55 UTC
**Describe the bug**
Occasionally, lumberjacks will remove only the bottom log, and then replant a sapling in its place.

**To Reproduce**
1. Plant a bunch of oak saplings
2. Bonemeal or wait for them to grow
3. Wait for choppage
4. Notice the odd behavior like the screenshots below

**Expected behavior**
Entire tree should be chopped, and then the sapling planted

**Screenshots**
![2019-05-26_16 14 04](https://user-images.githubusercontent.com/7838663/58415356-32395a00-804c-11e9-9700-c915502e38ed.png)
![2019-05-26_17 21 07](https://user-images.githubusercontent.com/7838663/58415360-35cce100-804c-11e9-9e8c-ce520be26b90.png)

** Server/Location **
SP, can send world file if needed

**Additional context**
I'm unsure if this is related to the proximity of the tree to a change in land height, but that might somehow be involved. I'll keep testing and let you know.

**Comment by JohnyDL** [comment] 2019-05-27 13:22
Duplicate of #46

**Comment by DEV4ST4TOR** [comment] 2019-05-27 15:59
We have the same problem

**Comment by TangoTek** [comment] 2019-05-29 04:56
Finally got this one fixed I believe.  Let me know if you see this beyond 1.0.18.  Thanks!

**Closed as completed by TangoTek** 2019-05-29 04:56 UTC

**Comment by Konyv** [comment] 2019-06-01 04:42
I had this issue earlier today around 12 noon SCT. 5-31-2019

![2019-05-31_12 48 08](https://user-images.githubusercontent.com/51104278/58743774-b51c3500-83fd-11e9-8fde-4145a7a5d59f.png)
![2019-05-31_12 48 35](https://user-images.githubusercontent.com/51104278/58743775-b6e5f880-83fd-11e9-90ee-fcaa2638fca2.png)
