### ISSUE TITLE
Bug - Enchanter not enchanting books

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#687] opened 2019-07-12 20:00 UTC
in jar 1.0.60 our enchanters have stopped enchanting books. They will go through the animations, gain levels and only consume lapis, not the books themselves.

**To Reproduce**
Have enchanter set to only enchant books.
watch as he goes through the animations but produces nothing.

**Expected behavior**
Enchanters make enchanted books.

**Screenshots**
![2019-07-12_20 54 03](https://user-images.githubusercontent.com/49371154/61155070-df2a4200-a4e7-11e9-83c2-8507661cb850.png)
You can see that the enchanter had 9 lapis.
![2019-07-12_20 54 19](https://user-images.githubusercontent.com/49371154/61155071-df2a4200-a4e7-11e9-836b-c1ec3244897c.png)
And now she has 8 but no enchanted book.

** Server/Location **
What if 1.

**Comment by Shamshalabim** [comment] 2019-07-12 20:32
Sober and I have put our enchanter through her paces on this one as it's easily testable by a player..
When set to enchant books ONLY the enchanter will bring in 2 books and 10 lapis . All villager items. She will then go through the motions of enchanting the book, showing the casting animation three times before it visually glitches a little and 'resets'. At this point she will have used 1 lapis, but no book, and no enchanted book will be created. She then repeats the process over and over until all ten lapis have been used. She will periodically gain levels in skill, but still no enchanted book will be produced.

We have set her to enchant various other items and they all seem to enchant up as intended. We have even seen Mending on a few.

**Comment by Caableguy** [comment] 2019-07-12 22:56
same thing is happening for me, lapis is going down with no enchanted book being created

**Comment by TangoTek** [comment] 2019-07-12 23:21
Fixed in 1.0.61.  Probably broken in 1.0.64.  Will attempt to fix in 1.0.65.  Broken again every third patch thereafter.

**Closed as completed by TangoTek** 2019-07-12 23:21 UTC

**Comment by Shamshalabim** [comment] 2019-07-13 00:28
Good to know.. We have faith!!
