### ISSUE TITLE
False Duplication of Town Hall marker

### ISSUE THREAD

**Issue by KingsKnight267** [TangoTek/TekTopia-Community#218] opened 2019-05-31 04:22 UTC
**Describe the bug**
When placing the townhall marker in a chest or in inventory and moving slots it falsely appears to duplicate. It eventually catches itself
**To Reproduce**
1. make marker (townhall)
2. move from inventory slot to another slot while clicking. 
3. Move from inventory to chest and repeat number 2.

**Expected behavior**
I expected the marker to seamlessly move between inventory and chest and not duplicate

**Screenshots**
![2019-05-31_00 14 15](https://user-images.githubusercontent.com/51222386/58681347-f9460180-8339-11e9-8bda-0238c4fe95f0.png)
![2019-05-31_00 13 19](https://user-images.githubusercontent.com/51222386/58681348-f9460180-8339-11e9-8feb-c40f901d9483.png)
![2019-05-31_00 13 32](https://user-images.githubusercontent.com/51222386/58681349-f9460180-8339-11e9-8d89-f12aab947553.png)
![2019-05-31_00 13 45](https://user-images.githubusercontent.com/51222386/58681350-f9460180-8339-11e9-9a58-2eee5a877ea5.png)
![2019-05-31_00 13 51](https://user-images.githubusercontent.com/51222386/58681351-f9460180-8339-11e9-9eea-f9f9be84f7cc.png)
![2019-05-31_00 14 00](https://user-images.githubusercontent.com/51222386/58681352-f9460180-8339-11e9-8251-a0b5a279775e.png)
![2019-05-31_00 14 03](https://user-images.githubusercontent.com/51222386/58681353-f9460180-8339-11e9-87d2-56a921ddf3ae.png)
![2019-05-31_00 14 09](https://user-images.githubusercontent.com/51222386/58681354-f9de9800-8339-11e9-8544-4a88f15c047b.png)
![2019-05-31_00 14 12](https://user-images.githubusercontent.com/51222386/58681355-f9de9800-8339-11e9-9527-f913a5a6cd45.png)
![2019-05-31_00 14 14](https://user-images.githubusercontent.com/51222386/58681356-f9de9800-8339-11e9-8a8b-7fe297ff395a.png)

** Server/Location **
Tektopia server 2 
-5557 x 71 x -176

**Additional context**
No additional comments to add at this time.

**Comment by JohnyDL** [comment] 2019-05-31 04:26
Duplicate of #60

**Closed as completed** 2019-06-01 08:12 UTC
Labels: duplicate

**Comment by SoulBrig** [comment] 2019-06-18 02:46
This exact issue happened to me tonight on Server 2 (10PM EST).  In my case it happened when I click-sorted while hovering over the Town Hall Token.  Perhaps this has something to do with the click sorting mod? So far I have been unable to duplicate this in a single player world.  I am available to test further if needed.

![2019-06-17_22 34 15](https://user-images.githubusercontent.com/16951254/59649572-27587d80-9151-11e9-90c4-3a26e9aba5eb.png)
