### ISSUE TITLE
jumberjack not dropping off inventory

### ISSUE THREAD

**Issue by ekkelos** [TangoTek/TekTopia-Community#271] opened 2019-06-02 19:27 UTC
in my village i have a lumberjack that has a full inventory and no axe in the inventory and now it is stuck because she wants to pickup a axe but cant because her inventory is full. i suspect the code is giving getting an axe priority over emptying the inventory. thus getting in a loop of i need and axe but my inventory is full but i really need that axe and just getting stuck in her house. 
![2019-06-02_20 26 35](https://user-images.githubusercontent.com/16520267/58766301-3221e880-857d-11e9-8ce8-a36a1aa82ba8.png)

**Comment by Geex204** [comment] 2019-06-02 19:31
This is posted several times now and seems to be fix in the next update.

**Comment by JohnyDL** [comment] 2019-06-02 19:51
Duplicate of #230 and #264

**Closed as completed** 2019-06-02 19:53 UTC
